[project]
name = "yapom"
version = "0.1.0"
description = "Yet Another Pomodoro app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.0",
]

[tool]
[tool.pyrefly]
project-includes = ["**/*"]
project-excludes = ["**/*venv/**/*"]
